### PR TITLE
@nightshining added example for ofxPJControl addon

### PR DESCRIPTION
**Pull request by nightshining**
Hello,
I was using your addon today and built out a small example for it. Hope it's helpful. Thanks again. 

--Mike

### CODE REVIEW

**Comment by nullboundary** [comment]
Hi Mike thanks for adding an example! Could you just delete the apps in bin/ ? Otherwise great.

**Comment by nullboundary** [comment]
Hi Mike, any chance you could remove the apps bin/ directory? I would like to merge this. Thanks!

**Comment by nightshining** [comment]
Hi, 
I removed the binary from that one example and actually updated our forked repo to have another example which is a timer setup with gui if you're still interested in merging the addon. Thanks so much!

**Comment by nullboundary** [comment]
Looks great. Thanks for your effort!

**Pull request merged**
